"""Sanity checks for core.py (run: .venv/bin/python test_core.py)."""

import numpy as np
import core
import z2_helpers
from core import (ModuleMap, compose, syzygies, ball, ball_types, w_mul, w_inv, E, BALL,
                  hermitian_transpose, ball_span, module_eq_on_ball, generate_infinite_code)
from z2_helpers import z2lin

rng = np.random.default_rng(0)


def words(diam):
    """ball(diam) as a list of words."""
    return [BALL.word(g) for g in ball(diam)]


def random_map(m, n, diam=2, density=0.3):
    """Random map with support inside ball(diam)."""
    S = words(diam)
    entries = {(i, j): [w for w in S if rng.random() < density]
               for i in range(m) for j in range(n)}
    return ModuleMap.from_entries(m, n, entries)


def as_dicts(f):
    return [[set(f.entry(i, j)) for j in range(f.n)] for i in range(f.m)]


def new_columns(A, B):
    """Indices of columns of B that are not in the span of A."""
    return z2_helpers.remove_image(A, B)[1]


# ------------------------------------------------------------------ ring arithmetic

def test_compose():
    """Compare compose() against a straightforward dict-based ring matrix product."""
    for _ in range(10):
        m, n, p = rng.integers(1, 4, size=3)
        f, g = random_map(m, n), random_map(n, p)
        F, G = as_dicts(f), as_dicts(g)
        ref = []
        for i in range(m):
            row = []
            for j in range(p):
                acc = {}
                for k in range(n):
                    for u in F[i][k]:
                        for v in G[k][j]:
                            w = w_mul(u, v)
                            acc[w] = acc.get(w, 0) ^ 1
                row.append({w for w, c in acc.items() if c})
            ref.append(row)
        assert as_dicts(compose(f, g)) == ref
    print("compose: ok")


def test_expand():
    """f.expand must agree with applying f entrywise to a random module element."""
    f = random_map(2, 3)
    S_in = ball(4)
    M, S_out = f.expand(S_in)
    x = rng.integers(0, 2, size=(f.n, len(S_in)))
    got = ((M @ x.reshape(-1)) % 2).reshape(f.m, len(S_out))
    ref = [{} for _ in range(f.m)]
    for i in range(f.m):
        for j in range(f.n):
            for u in f.entry(i, j):
                for gi, g in enumerate(S_in):
                    if x[j, gi]:
                        h = w_mul(u, BALL.word(g))
                        ref[i][h] = ref[i].get(h, 0) ^ 1
    for i in range(f.m):
        for k, h in enumerate(S_out):
            assert got[i, k] == ref[i].get(BALL.word(h), 0)
    print("expand: ok")


def test_shift_commutes():
    """Right translation commutes with f: f*(g*w) == (f*g)*w."""
    f, g = random_map(2, 3), random_map(3, 2)
    w = (1, -2)
    assert as_dicts(compose(f, g.shifted(w))) == as_dicts(compose(f, g).shifted(w))
    print("shift: ok")


# ------------------------------------------------------------------------ syzygies

def check_syzygy(f, max_diam, expect_counts=None, name="", margin_rad=0, same_diam_pruning=True):
    g = syzygies(f, max_diam, margin_rad, same_diam_pruning)
    assert compose(f, g).is_zero(), f"{name}: f*g != 0"
    # each generator has support diameter exactly its level, and sits in that ball
    assert list(g.diams()) == g.gen_diams, f"{name}: diams {g.diams()} != levels {g.gen_diams}"
    for j, (d, s) in enumerate(zip(g.gen_diams, g.gen_types)):
        assert np.isin(g.column(j).support, ball(d, s)).all(), f"{name}: generator {j} not in its ball"
    # the kernel on the diameter-max_diam balls lies in the R-module generated by g; the
    # witnesses can stick out by margin_rad, we check on ball(2*max_diam)
    W = ball(2 * max_diam)
    for s in ball_types(max_diam):
        S = ball(max_diam, s)
        ker = z2lin.kernel(f.expand(S)[0])
        ker_W = np.zeros((f.n, len(W), ker.shape[1]), dtype=int)
        ker_W[:, np.searchsorted(W, S)] = ker.reshape(f.n, len(S), -1)
        assert not new_columns(ball_span(g, 2 * max_diam), ker_W.reshape(f.n * len(W), -1)), \
            f"{name}: kernel not covered by image of g"
    # no generator is in the span of the translates of the smaller generators (plus the
    # same-diameter ones if same_diam_pruning) inside its ball enlarged by margin_rad, and
    # of all generators of at most its diameter inside its own ball
    for j, (d, s) in enumerate(zip(g.gen_diams, g.gen_types)):
        for Wj, dmax in [(ball(d + 2 * margin_rad, s), d if same_diam_pruning else d - 1), (ball(d, s), d)]:
            others = [core.translates(g.column(k), Wj) for k in range(g.n) if k != j and g.gen_diams[k] <= dmax]
            assert new_columns(core._hstack(others, f.n * len(Wj)), g.column(j).dense_columns(Wj)), \
                f"{name}: generator {j} redundant"
    if expect_counts is not None:
        assert g.level_counts == expect_counts, f"{name}: counts {g.level_counts} != {expect_counts}"
    return g


def test_syzygies():
    a, b, ainv = (1,), (2,), (-1,)

    # augmentation ideal: (1+a, 1+b) is free of rank 2 -> no syzygies
    f = ModuleMap.from_entries(1, 2, {(0, 0): [E, a], (0, 1): [E, b]})
    g = check_syzygy(f, 4, [0, 0, 0, 0, 0], "augmentation ideal")
    assert g.n == 0

    # (1+a, 1+a): kernel generated by (1,1), found at diam=0
    f = ModuleMap.from_entries(1, 2, {(0, 0): [E, a], (0, 1): [E, a]})
    g = check_syzygy(f, 4, [1, 0, 0, 0, 0], "(1+a,1+a)")
    assert g.n == 1 and g.entry(0, 0) == [E] and g.entry(1, 0) == [E]

    # (1+a, 1+a^-1) = (1+a)*(1, a^-1): kernel generated by (a^-1, 1) ~ (1, a), of
    # diameter 1.  Of its translates only (1, a) fits in the edge ball {e, a} = ball(1, 0),
    # and none in {e, b}; the radius-1 ball ball(2) contains two of them.
    f = ModuleMap.from_entries(1, 2, {(0, 0): [E, a], (0, 1): [E, ainv]})
    g = check_syzygy(f, 4, [0, 1, 0, 0, 0], "(1+a,1+ainv)")
    assert g.n == 1 and g.entry(0, 0) == [E] and g.entry(1, 0) == [a] and g.gen_types == [0]

    # (1+a, (1+a)ab): kernel generated by (ab, 1) ~ its translate (a, b^-1), diameter 2
    f = ModuleMap.from_entries(1, 2, {(0, 0): [E, a], (0, 1): [(1, 2), (1, 1, 2)]})
    g = check_syzygy(f, 6, [0, 0, 1, 0, 0, 0, 0], "(1+a,(1+a)ab)")
    assert g.n == 1 and g.entry(0, 0) == [a] and g.entry(1, 0) == [(-2,)]

    # injective map -> no syzygies
    f = ModuleMap.from_entries(2, 2, {(0, 0): [E, a], (1, 1): [E, b], (0, 1): [a]})
    check_syzygy(f, 4, [0, 0, 0, 0, 0], "triangular")

    # random maps with more inputs than outputs
    for m, n in [(1, 2), (1, 3), (2, 3)]:
        f = random_map(m, n, diam=2, density=0.3)
        for max_diam, margin, same in [(4, 0, True), (5, 0, False), (4, 1, True), (5, 1, False)]:
            g = check_syzygy(f, max_diam, name=f"random {m}x{n}", margin_rad=margin, same_diam_pruning=same)
            print(f"  random {m}x{n}, max_diam={max_diam}, margin={margin}, same-diam pruning={same}: "
                  f"level counts {g.level_counts}")
    print("syzygies: ok")


# ------------------------------------------------------------- dagger / infinite code

def test_dagger():
    f, g = random_map(2, 3), random_map(3, 2)
    fd = hermitian_transpose(f)
    # entrywise definition and involutivity
    for i in range(f.m):
        for j in range(f.n):
            assert set(fd.entry(j, i)) == {w_inv(u) for u in f.entry(i, j)}
    assert as_dicts(hermitian_transpose(fd)) == as_dicts(f)
    # anti-multiplicativity
    assert as_dicts(hermitian_transpose(compose(f, g))) == \
           as_dicts(compose(hermitian_transpose(g), hermitian_transpose(f)))
    print("dagger: ok")


def test_pairing():
    """
    y^dagger x = 0  <=>  every translate of (the columns of) y has even overlap with
    every translate of (the columns of) x.  Checked by brute force on a ball.
    """
    n, diam = 2, 2
    S = ball(diam)
    x = ModuleMap(S, rng.integers(0, 2, size=(n * len(S), 1)), n).trimmed()
    y = ModuleMap(S, rng.integers(0, 2, size=(n * len(S), 1)), n).trimmed()
    prod = compose(hermitian_transpose(y), x)  # a single ring element (1 x 1 matrix)
    # overlap of x*u and y*v, as dicts over (coordinate, word)
    def cells(z, w):
        return {(i, w_mul(u, w)) for i in range(z.m) for u in z.entry(i, 0)}
    for u in words(2 * diam):
        for v in words(2 * diam):
            overlap = len(cells(x, u) & cells(y, v)) % 2
            # <y v, x u> = coefficient of (y^dagger x) at v u^-1
            assert overlap == int(w_mul(v, w_inv(u)) in prod.entry(0, 0))
    print("pairing: ok")


def test_infinite_code():
    """
    The defining property of step 2: H_X = ker(H_Z^dagger), i.e. the triple annihilator
    equals the single one.  Checked on ball(2*max_diam).
    """
    max_diam = 4
    for (n, m, w) in [(3, 1, 3), (3, 2, 4), (4, 2, 4)]:
        f = core.random_gens(n, m, diam=2, w=w, rng=rng)
        H_X, H_Z = generate_infinite_code(n, m, max_diam, init_diam=2, w_init=w, f=f)
        assert compose(hermitian_transpose(H_X), H_Z).is_zero(), "H_X, H_Z do not commute"
        # the initial Z operators must reappear inside im(H_Z)
        assert not new_columns(ball_span(H_Z, 2 * max_diam), ball_span(f, 2 * max_diam)), "f not inside im(H_Z)"
        H_X3 = syzygies(hermitian_transpose(H_Z), max_diam)
        # im(H_X) is always contained in im(H_X3); equality is the claim being tested
        assert not new_columns(ball_span(H_X3, 2 * max_diam), ball_span(H_X, 2 * max_diam))
        eq = module_eq_on_ball(H_X, H_X3, 2 * max_diam)
        print(f"  n={n} m={m} w={w}: {H_X.n} X-gens {H_X.level_counts}, "
              f"{H_Z.n} Z-gens {H_Z.level_counts}, H_X == ker(H_Z^dagger): {eq}")
        assert eq, "H_X != ker(H_Z^dagger) on ball(2*max_diam)"
    print("infinite code: ok")


def test_euler_sum():
    """
    cayley_codes.md claims the number of X plus Z stabilizers per vertex is exactly n
    for G = F_2.  The raw generator counts k_X + k_Z can exceed n (the returned
    generators need not be R-independent -- a relation may only be visible on a larger
    ball than max_diam), but the Euler sum of the free resolution should give n.
    """
    max_diam, over = 6, 0
    for (n, m, w) in [(3, 1, 3), (4, 2, 4), (5, 2, 5), (5, 3, 4)]:
        for _ in range(4):
            H_X, H_Z = generate_infinite_code(n, m, max_diam, init_diam=2, w_init=w, rng=rng)
            s_X, s_Z = syzygies(H_X, max_diam), syzygies(H_Z, max_diam)
            assert s_X.n == 0 or compose(H_X, s_X).is_zero()
            euler = H_X.n - s_X.n + H_Z.n - s_Z.n
            over += (H_X.n + H_Z.n) - n
            assert euler == n, f"n={n}: kX={H_X.n} kZ={H_Z.n} sX={s_X.n} sZ={s_Z.n}"
    print(f"euler sum: ok  (raw generator counts were redundant by {over} in total)")


# --------------------------------------------------------------- compactification

def test_compactification():
    """reduce_word is a homomorphism and left_perm is left multiplication."""
    comp = core.psl2p(5)
    assert comp.N == 60  # PSL(2,5) = A_5
    words = [E, (1,), (-2,), (1, 2), (2, -1, 2), (1, 1, 1, -2, 1)]
    for u in words:
        Lu = comp.left_perm(u)
        for v in words:
            assert Lu[comp.reduce_word(v)] == comp.reduce_word(w_mul(u, v))
        assert comp.reduce_word(w_mul(u, w_inv(u))) == 0
    # left multiplications are permutations and commute with right multiplications
    for x in core.GENS:
        assert sorted(comp.L[x]) == list(range(comp.N))
        for y in core.GENS:
            assert np.array_equal(comp.L[x][comp.R[y]], comp.R[y][comp.L[x]])
    print("compactification: ok")


def test_girth():
    """find_girth against brute force over all reduced words in a ball."""
    L = 6  # radius
    for comp, name in [(core.psl2p(5), "PSL(2,5)"), (core.psl2p(7), "PSL(2,7)"),
                       (core.psl2p(11), "PSL(2,11)"), (core.psl2p(13), "PSL(2,13)")]:
        g = comp.find_girth()
        brute = min((len(w) for w in words(2 * L) if w and comp.reduce_word(w) == 0), default=np.inf)
        assert (g == brute) if g <= L else (brute == np.inf), f"{name}: {g} vs brute {brute}"
        print(f"  {name}: |G|={comp.N}, girth={g}")
    # a tiny quotient with short relations: Z_2 x Z_3 (a^2 = b^3 = [a,b] = 1)
    comp = core.Compactification.from_group((0, 0), (1, 0), (0, 1),
                                            lambda x, y: ((x[0] + y[0]) % 2, (x[1] + y[1]) % 3))
    assert comp.N == 6 and comp.find_girth() == 2  # a^2 = e
    print("girth: ok")


def test_compactify():
    """
    compactify must be a ring homomorphism on maps, send dagger to transpose, and hence
    turn the infinite CSS code into a finite one.
    """
    comp = core.psl2p(5)
    N = comp.N

    # (1) entrywise definition, using only reduce_word
    f = random_map(2, 3, diam=4)
    M = f.compactify(comp)
    for v in [E, (1,), (1, -2), (2, 2, 1)]:
        d = comp.reduce_word(v)
        for i in range(f.m):
            for j in range(f.n):
                acc = np.zeros(N, dtype=int)
                for u in f.entry(i, j):
                    acc[comp.reduce_word(w_mul(u, v))] ^= 1
                assert np.array_equal(M[i * N:(i + 1) * N, j * N + d], acc)

    # (2) functoriality and dagger -> transpose
    g = random_map(3, 2, diam=2)
    assert np.array_equal(core.compose(f, g).compactify(comp), (M @ g.compactify(comp)) % 2)
    assert np.array_equal(hermitian_transpose(f).compactify(comp), M.T)

    # (3) a finite CSS code
    for (n, m, w) in [(3, 1, 3), (4, 2, 4)]:
        H_X, H_Z = generate_infinite_code(n, m, max_diam=4, init_diam=2, w_init=w, rng=rng)
        AX, AZ = H_X.compactify(comp).T, H_Z.compactify(comp).T  # rows = stabilizers
        assert not (AX @ AZ.T % 2).any(), "compactified code is not CSS-commuting"
        rX, rZ = len(z2_helpers.injectify(AX.T)), len(z2_helpers.injectify(AZ.T))
        print(f"  n={n} m={m}: [[{n * N}, {n * N - rX - rZ}]] "
              f"(rank X {rX}/{H_X.n * N}, rank Z {rZ}/{H_Z.n * N})")
    print("compactify: ok")


if __name__ == "__main__":
    test_compose()
    test_expand()
    test_shift_commutes()
    test_syzygies()
    test_dagger()
    test_pairing()
    test_infinite_code()
    test_euler_sum()
    test_compactification()
    test_girth()
    test_compactify()
    print("all ok")
