"""Sanity checks for core.py (run: .venv/bin/python test_core.py)."""

import numpy as np
import core
import z2_helpers
from core import ModuleMap, compose, syzygies, star, w_mul, E
from z2_helpers import z2lin

rng = np.random.default_rng(0)


def random_map(m, n, l=1, density=0.3):
    """Random map with support inside the depth-l star."""
    S = star(l)
    entries = {(i, j): [w for w in S if rng.random() < density]
               for i in range(m) for j in range(n)}
    return ModuleMap.from_entries(m, n, entries)


def as_dicts(f):
    return [[set(f.entry(i, j)) for j in range(f.n)] for i in range(f.m)]


def new_columns(A, B):
    """Indices of columns of B that are not in the span of A."""
    return z2_helpers.remove_image(A, B)[1]


# ------------------------------------------------------------------ ring arithmetic

def test_compose():
    """Compare compose() against a straightforward dict-based ring matrix product."""
    for _ in range(10):
        m, n, p = rng.integers(1, 4, size=3)
        f, g = random_map(m, n), random_map(n, p)
        F, G = as_dicts(f), as_dicts(g)
        ref = []
        for i in range(m):
            row = []
            for j in range(p):
                acc = {}
                for k in range(n):
                    for u in F[i][k]:
                        for v in G[k][j]:
                            w = w_mul(u, v)
                            acc[w] = acc.get(w, 0) ^ 1
                row.append({w for w, c in acc.items() if c})
            ref.append(row)
        assert as_dicts(compose(f, g)) == ref
    print("compose: ok")


def test_expand():
    """f.expand must agree with applying f entrywise to a random module element."""
    f = random_map(2, 3)
    S_in = star(2)
    M, S_out = f.expand(S_in)
    x = rng.integers(0, 2, size=(f.n, len(S_in)))
    got = ((M @ x.reshape(-1)) % 2).reshape(f.m, len(S_out))
    ref = [{} for _ in range(f.m)]
    for i in range(f.m):
        for j in range(f.n):
            for u in f.entry(i, j):
                for gi, g in enumerate(S_in):
                    if x[j, gi]:
                        h = w_mul(u, g)
                        ref[i][h] = ref[i].get(h, 0) ^ 1
    for i in range(f.m):
        for k, h in enumerate(S_out):
            assert got[i, k] == ref[i].get(h, 0)
    print("expand: ok")


def test_shift_commutes():
    """Right translation commutes with f: f*(g*w) == (f*g)*w."""
    f, g = random_map(2, 3), random_map(3, 2)
    w = (1, -2)
    assert as_dicts(compose(f, g.shifted(w))) == as_dicts(compose(f, g).shifted(w))
    print("shift: ok")


# ------------------------------------------------------------------------ syzygies

def check_syzygy(f, l_max, expect_counts=None, name=""):
    g = syzygies(f, l_max)
    assert compose(f, g).is_zero(), f"{name}: f*g != 0"
    for l in range(l_max + 1):
        Sl = star(l)
        Sl_idx = {w: k for k, w in enumerate(Sl)}
        ker = z2lin.kernel(f.expand(Sl)[0])
        # all translates of the generators of g that fit inside the depth-l star
        cols = [x.shifted(w).dense_columns(Sl_idx)
                for x in map(g.column, range(g.n))
                for w in core._valid_shifts(x.support, set(Sl))]
        span = np.hstack(cols) if cols else np.zeros((f.n * len(Sl), 0), dtype=int)
        assert not new_columns(span, ker), f"{name}: kernel at l={l} not covered by image of g"
        # ... and conversely the translates must be kernel elements
        assert not (f.expand(Sl)[0] @ span % 2).any(), f"{name}: translates not in kernel"
    if expect_counts is not None:
        assert g.level_counts == expect_counts, f"{name}: counts {g.level_counts} != {expect_counts}"
    return g


def test_syzygies():
    a, b, ainv = (1,), (2,), (-1,)

    # augmentation ideal: (1+a, 1+b) is free of rank 2 -> no syzygies
    f = ModuleMap.from_entries(1, 2, {(0, 0): [E, a], (0, 1): [E, b]})
    g = check_syzygy(f, 2, [0, 0, 0], "augmentation ideal")
    assert g.n == 0

    # (1+a, 1+a): kernel generated by (1,1), found at l=0
    f = ModuleMap.from_entries(1, 2, {(0, 0): [E, a], (0, 1): [E, a]})
    g = check_syzygy(f, 2, [1, 0, 0], "(1+a,1+a)")
    assert g.n == 1 and g.entry(0, 0) == [E] and g.entry(1, 0) == [E]

    # (1+a, 1+a^-1) = (1+a)*(1, a^-1): kernel generated by (a^-1, 1), new at l=1.
    # Its translate by a is also supported on the depth-1 star, so this checks that
    # translates of same-depth generators are quotiented out too.
    f = ModuleMap.from_entries(1, 2, {(0, 0): [E, a], (0, 1): [E, ainv]})
    g = check_syzygy(f, 2, [0, 1, 0], "(1+a,1+ainv)")
    assert g.n == 1 and g.entry(0, 0) == [ainv] and g.entry(1, 0) == [E]

    # (1+a, (1+a)ab): kernel generated by (ab, 1) ~ its translate (a, b^-1) at depth 1
    f = ModuleMap.from_entries(1, 2, {(0, 0): [E, a], (0, 1): [(1, 2), (1, 1, 2)]})
    g = check_syzygy(f, 3, [0, 1, 0, 0], "(1+a,(1+a)ab)")
    assert g.n == 1 and g.entry(0, 0) == [a] and g.entry(1, 0) == [(-2,)]

    # injective map -> no syzygies
    f = ModuleMap.from_entries(2, 2, {(0, 0): [E, a], (1, 1): [E, b], (0, 1): [a]})
    check_syzygy(f, 2, [0, 0, 0], "triangular")

    # random maps with more inputs than outputs
    for m, n in [(1, 2), (1, 3), (2, 3)]:
        f = random_map(m, n, l=1, density=0.3)
        g = check_syzygy(f, 2, name=f"random {m}x{n}")
        print(f"  random {m}x{n}: level counts {g.level_counts}")
    print("syzygies: ok")


if __name__ == "__main__":
    test_compose()
    test_expand()
    test_shift_commutes()
    test_syzygies()
    print("all ok")
